### ISSUE TITLE
Reference files

### ISSUE THREAD

**Issue by mdozmorov** [ArimaGenomics/Arima-SV-Pipeline#2]
Hi. Would it be possible to share the reference files, like `hg38.chrom.sizes`, `hg38_GATC_GANTC.txt`, `Digest_hg38_Arima.txt`, `intra_expect_100kb.hg38.txt`, `inter_expect_1Mb.hg38.txt`? I'm not sure about the format and source for some of them. Trying to create a Conda environment as our HPC won't allow Docker/Singularity.

**Comment by xz-000** [comment]
Yes, please contact our tech support at: techsupport@arimagenomics.com . They will provide you those files, thanks!
